### ISSUE TITLE
not working on boxes without FTP server

### ISSUE THREAD

**Issue by mokkin** [jens-maus/carddav2fb#5] opened 2015-07-31 13:33 UTC
I tried to upload an addressbook to my 7312 at home, but it failed. Probably it will fail on all simple boxes without FTP server like 7312, 7412, 7112, 7113.
On my office box 7390 it works fine copying the pictures to the attached USB device.
```
$config['usb_disk'] = '';
```
```
...
PHP Warning:  ftp_close() expects parameter 1 to be resource, boolean given in /var/www/carddav2fb/carddav2fb2.php on line 474
 Uploading Phonebook XML
  ERROR: Response of initialization call /login_sid.lua in initSID was not xml-formatted.
Done.
```

**Comment by mecks52** [comment] 2015-07-31 16:33
I think there are two "issues", the box has no ftp to store the pictures is one but the line
``` 
ERROR: Response of initialization call /login_sid.lua in initSID was not xml-formatted.
```
shows up after the ftp part of the script has already finished. If it is the main issue you can't upload the phonebook, it seems to have an other root cause and nothing to do with the missing ftp-functionality.

**Comment by mokkin** [comment] 2015-08-05 20:57
I'm watching the same behavior with a 7270. Both, the 7312 and this 7270 are connected via VPN. Maybe this is part of the problem.

**Comment by jens-maus** [comment] 2016-05-17 08:45
The FTP issue has been already "solved" by having added some warning/error output. The other issue "initSID" error is however a duplicate of #15 and discussed there instead.

**Closed by jens-maus** 2016-05-17 08:45 UTC
